### ISSUE TITLE
Invalid Velocity and Acceleration Output?

### ISSUE THREAD

**Issue by chris-ferone** [OxfordTechnicalSolutions/oxts_ros2_driver#6]
Hi, I'm seeing linear velocity and acceleration values published by the driver that I believe are incorrect. I've logged ros2 bags and am visualizing them with Foxglove Studio. The latitude, longitude, and altitude all look reasonable, its just the velocities and accelerations that doesn't seem right. Here's a screenshot of data from a test in which I drove a vehicle due south for a short distance.  
![oxts_debug8](https://user-images.githubusercontent.com/26842614/145501545-531706b3-834f-4f29-9ec2-8a3772be451f.png)
Here is a screenshot from NavGraph of data from the same time period of the velocity. You can verify its the same time period by comparing the Unix timestamp in the Foxglove studio screenshot to the GPS time listed i nthe NavGraph screenshots.
![image](https://user-images.githubusercontent.com/26842614/145501775-ce12de30-b641-4c98-82ad-ed7ab7fe0fc9.png)
And here is a screenshot for acceleration
![image](https://user-images.githubusercontent.com/26842614/145501820-a4e69b4c-0e75-4112-b198-4ff0882ff96d.png)
The data from NavGraph looks correct, however, the ros2 data does not match.

**Comment by ljones-oxts** [comment]
Hi Chris

My apologies for the late reply.

I notice on the "acceleration x" graph on the first graphic that it looks suspiciously like a z-axis acceleration (since it seems to settle on around 9.8m/s^2, which would indicate that it's measuring gravity).

Leading down this line of enquiry, I've a question for you: in which frame (IMU, or Vehicle) are you displaying the data in NAVgraph? The ROS2 driver always outputs velocities, accelerations and angular velocities in the IMU frame. I suspect the data mismatch stems from this reference frame mismatch.

Regards

Llyr

**Comment by chris-ferone** [comment]
Hi Llyr, 

Thanks so much for your reply. It appears I made another silly mistake. You are absolutely right in that the data is being correctly published in the oxts_link frame, given that our unit is oriented like so: 
![image](https://user-images.githubusercontent.com/26842614/146817874-2cad28ce-8b0c-4947-b222-9b20f37aa39a.png)

Here's the correct data: 
![image](https://user-images.githubusercontent.com/26842614/146818062-5ceb2bff-736f-428a-bf20-af8e203576e6.png)


I just need to create a coordinate transformation from oxts_link to the standard "base_link" frame I was (incorrectly) expecting to see. 

Thanks again, 
Chris
